package ubiquisense.iorx.protocols.midi.internal.dsl;


public enum MidiCmdEnum {
	NOTE_ON,
	NOTE_OFF,
	ACTIVE_SENSING,
	CHANNEL_PRESSURE,
	CONTINUE_SONG,
	CONTROLLER_CHANGE,
	END_OF_EXCLUSIVE,
	KEY_PRESSURE,
	MIDI_MESSAGE,
	PITCH_BEND,
	PROGRAM_CHANGE,
	SONG_POSITION,
	SONG_SELECT,
	START_SONG,
	STOP_SONG,
	SYSTEM_EXCLUSIVE,
	SYSTEM_RESET;

}
