package ubiquisense.iorx.ui.fmurf;

public enum SmurfAspect {
	SMURF_ASPECT_TRANSPARENT,
	SMURF_ASPECT_DISC,
	SMURF_ASPECT_SQUARE,
	SMURF_ASPECT_TRIANGLE,
	SMURF_ASPECT_STAR/*,
	SMURF_ASPECT_HEXAGON,
	SMURF_ASPECT_OCTOGON,
	SMURF_ASPECT_SIX_STAR,
	SMURF_ASPECT_HEIGHT_STAR,
	SMURF_ASPECT_CUSTOM*/
}